/**
 * DBMS theory content for the project.
 * Covers schema, keys, functional dependencies, normalization,
 * relational algebra, transactions, indexing — everything a
 * DBMS course expects to see documented for the project.
 */

export interface AttributeDef {
  name: string;
  type: string;
  nullable: boolean;
  defaultVal?: string;
  notes?: string;
}

export interface TableDoc {
  name: string;
  purpose: string;
  attributes: AttributeDef[];
  primaryKey: string[];
  candidateKeys: string[][];
  superKeys: string[][];
  foreignKeys: { columns: string[]; references: string }[];
  functionalDependencies: { lhs: string[]; rhs: string[]; note?: string }[];
  normalization: {
    onenf: string;
    twonf: string;
    threenf: string;
    bcnf: string;
    finalForm: "1NF" | "2NF" | "3NF" | "BCNF";
  };
  indexes: { name: string; columns: string[]; type: string; reason: string }[];
  rlsPolicies: { name: string; command: string; rule: string }[];
}

export const PROFILES_TABLE: TableDoc = {
  name: "profiles",
  purpose:
    "Stores extended user information (display name, avatar) keyed to the authenticated user. Created automatically by a trigger when a new user signs up.",
  attributes: [
    { name: "id", type: "UUID", nullable: false, defaultVal: "gen_random_uuid()", notes: "Surrogate primary key" },
    { name: "user_id", type: "UUID", nullable: false, notes: "References auth.users(id), unique per profile" },
    { name: "display_name", type: "TEXT", nullable: true },
    { name: "avatar_url", type: "TEXT", nullable: true },
    { name: "created_at", type: "TIMESTAMPTZ", nullable: false, defaultVal: "now()" },
    { name: "updated_at", type: "TIMESTAMPTZ", nullable: false, defaultVal: "now()", notes: "Maintained by trigger" },
  ],
  primaryKey: ["id"],
  candidateKeys: [["id"], ["user_id"]],
  superKeys: [["id"], ["user_id"], ["id", "user_id"], ["id", "display_name"]],
  foreignKeys: [{ columns: ["user_id"], references: "auth.users(id)" }],
  functionalDependencies: [
    { lhs: ["id"], rhs: ["user_id", "display_name", "avatar_url", "created_at", "updated_at"], note: "PK determines all attributes" },
    { lhs: ["user_id"], rhs: ["id", "display_name", "avatar_url", "created_at", "updated_at"], note: "user_id is also a candidate key" },
  ],
  normalization: {
    onenf: "All attributes are atomic (no repeating groups, no multi-valued columns).",
    twonf: "Primary key is a single column, so no partial dependency is possible — automatically in 2NF.",
    threenf: "No transitive dependencies between non-key attributes (display_name, avatar_url, timestamps are independent).",
    bcnf: "Every non-trivial FD has a candidate key (id or user_id) on its LHS, so the relation is in BCNF.",
    finalForm: "BCNF",
  },
  indexes: [
    { name: "profiles_pkey", columns: ["id"], type: "B-Tree (Unique)", reason: "Primary key lookup" },
    { name: "profiles_user_id_key", columns: ["user_id"], type: "B-Tree (Unique)", reason: "Enforces 1:1 with auth.users and speeds up auth-based lookups" },
  ],
  rlsPolicies: [
    { name: "Users can view their own profile", command: "SELECT", rule: "auth.uid() = user_id" },
    { name: "Users can insert their own profile", command: "INSERT", rule: "auth.uid() = user_id" },
    { name: "Users can update their own profile", command: "UPDATE", rule: "auth.uid() = user_id" },
  ],
};

export const PREDICTION_HISTORY_TABLE: TableDoc = {
  name: "prediction_history",
  purpose:
    "Stores every drought-risk prediction generated by the AI model along with the input features (region, population, temperature, rainfall) and computed outputs (risk level, water security score, recommendations).",
  attributes: [
    { name: "id", type: "UUID", nullable: false, defaultVal: "gen_random_uuid()", notes: "Surrogate primary key" },
    { name: "user_id", type: "UUID", nullable: false, notes: "Owner of the prediction" },
    { name: "region", type: "TEXT", nullable: false, notes: "Geographic region (input feature)" },
    { name: "population", type: "TEXT", nullable: true, notes: "Population bucket (input feature)" },
    { name: "avg_temp", type: "TEXT", nullable: true, notes: "Average temperature input" },
    { name: "avg_rainfall", type: "TEXT", nullable: true, notes: "Average rainfall input" },
    { name: "drought_risk", type: "TEXT", nullable: false, notes: "Output: Minimal / Low / Moderate / High / Severe" },
    { name: "rainfall_forecast", type: "TEXT", nullable: true, notes: "Output: textual forecast" },
    { name: "water_security_score", type: "INTEGER", nullable: true, notes: "Output: 0–100 score" },
    { name: "details", type: "TEXT", nullable: true, notes: "Output: model explanation" },
    { name: "recommendations", type: "TEXT[]", nullable: true, notes: "Output: list of suggested actions" },
    { name: "created_at", type: "TIMESTAMPTZ", nullable: false, defaultVal: "now()" },
  ],
  primaryKey: ["id"],
  candidateKeys: [["id"]],
  superKeys: [["id"], ["id", "user_id"], ["id", "region"], ["id", "created_at"]],
  foreignKeys: [{ columns: ["user_id"], references: "auth.users(id)" }],
  functionalDependencies: [
    { lhs: ["id"], rhs: ["user_id", "region", "population", "avg_temp", "avg_rainfall", "drought_risk", "rainfall_forecast", "water_security_score", "details", "recommendations", "created_at"], note: "PK → all attributes" },
    { lhs: ["region", "avg_temp", "avg_rainfall"], rhs: ["drought_risk", "water_security_score"], note: "Model FD: same input features deterministically yield the same risk/score (illustrative)" },
    { lhs: ["drought_risk"], rhs: [], note: "drought_risk does not determine any other attribute (categorical label only)" },
  ],
  normalization: {
    onenf: "All attributes atomic — recommendations is stored as a Postgres ARRAY which still satisfies 1NF in the relational-with-arrays model used here.",
    twonf: "Single-column PK, so no partial dependencies — trivially in 2NF.",
    threenf: "Non-key attributes do not depend on other non-key attributes; the model FD (region, avg_temp, avg_rainfall → drought_risk) is treated as application logic, not a stored dependency.",
    bcnf: "Strictly speaking, if (region, avg_temp, avg_rainfall) → drought_risk were enforced in the schema, the table would only be in 3NF (the LHS is not a superkey). Since the prediction is computed and stored per request, the relation is treated as in BCNF.",
    finalForm: "3NF",
  },
  indexes: [
    { name: "prediction_history_pkey", columns: ["id"], type: "B-Tree (Unique)", reason: "Primary key lookup" },
    { name: "idx_prediction_user_created", columns: ["user_id", "created_at"], type: "B-Tree (recommended)", reason: "Speeds up the History page query that filters by user and orders by date" },
  ],
  rlsPolicies: [
    { name: "Users can view their own predictions", command: "SELECT", rule: "auth.uid() = user_id" },
    { name: "Users can insert their own predictions", command: "INSERT", rule: "auth.uid() = user_id" },
    { name: "Users can delete their own predictions", command: "DELETE", rule: "auth.uid() = user_id" },
  ],
};

export const ALL_TABLES: TableDoc[] = [PROFILES_TABLE, PREDICTION_HISTORY_TABLE];

/* -------------------- ER diagram (text form) -------------------- */

export const ER_DIAGRAM = `
  ┌──────────────────────┐         ┌─────────────────────────────┐
  │     auth.users       │ 1     1 │          profiles           │
  │──────────────────────│─────────│─────────────────────────────│
  │ id (PK)              │         │ id (PK)                     │
  │ email                │         │ user_id (FK, UNIQUE)        │
  │ raw_user_meta_data   │         │ display_name                │
  └──────────────────────┘         │ avatar_url                  │
            │                      │ created_at, updated_at      │
            │ 1                    └─────────────────────────────┘
            │
            │ N
  ┌────────────────────────────────────────────────────────┐
  │                  prediction_history                    │
  │────────────────────────────────────────────────────────│
  │ id (PK)                                                │
  │ user_id (FK → auth.users.id)                           │
  │ region, population, avg_temp, avg_rainfall   (inputs)  │
  │ drought_risk, rainfall_forecast,                       │
  │ water_security_score, details, recommendations[]       │
  │ created_at                                             │
  └────────────────────────────────────────────────────────┘

  Cardinality:
    auth.users (1) ───── (1) profiles            (one-to-one)
    auth.users (1) ───── (N) prediction_history  (one-to-many)
`;

/* -------------------- Relational algebra -------------------- */

export const RELATIONAL_ALGEBRA = [
  {
    title: "Fetch a user's prediction history (Selection + Projection)",
    expression: "π region, drought_risk, water_security_score, created_at ( σ user_id = :uid ( prediction_history ) )",
    sql: `SELECT region, drought_risk, water_security_score, created_at
FROM prediction_history
WHERE user_id = auth.uid();`,
  },
  {
    title: "Join profiles with their predictions (Natural Join)",
    expression: "π display_name, region, drought_risk ( profiles ⋈ profiles.user_id = ph.user_id prediction_history )",
    sql: `SELECT p.display_name, ph.region, ph.drought_risk
FROM profiles p
JOIN prediction_history ph ON p.user_id = ph.user_id;`,
  },
  {
    title: "Aggregate: count predictions per risk level (Group-by γ)",
    expression: "γ drought_risk; COUNT(*) → cnt ( prediction_history )",
    sql: `SELECT drought_risk, COUNT(*) AS cnt
FROM prediction_history
GROUP BY drought_risk
ORDER BY cnt DESC;`,
  },
  {
    title: "High-risk regions (Selection + Projection + Distinct)",
    expression: "δ ( π region ( σ drought_risk IN {'High','Severe'} ( prediction_history ) ) )",
    sql: `SELECT DISTINCT region
FROM prediction_history
WHERE drought_risk IN ('High', 'Severe');`,
  },
];

/* -------------------- Triggers & functions -------------------- */

export const DB_FUNCTIONS = [
  {
    name: "public.handle_new_user()",
    purpose: "Automatically create a profile row whenever a new auth.users row is inserted (trigger function).",
    sql: `CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  INSERT INTO public.profiles (user_id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email));
  RETURN NEW;
END;
$$;`,
  },
  {
    name: "public.update_updated_at_column()",
    purpose: "Generic BEFORE UPDATE trigger function that refreshes the updated_at timestamp on any table that uses it.",
    sql: `CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;`,
  },
];

/* -------------------- Transactions / ACID example -------------------- */

export const TRANSACTION_EXAMPLE = `-- ACID-compliant transaction: save a prediction and log it atomically.
-- If any statement fails, the whole transaction rolls back (Atomicity).
BEGIN;

  INSERT INTO prediction_history
    (user_id, region, population, avg_temp, avg_rainfall,
     drought_risk, water_security_score, details)
  VALUES
    (auth.uid(), 'Marathwada', '8M', '32', '450',
     'High', 38, 'Below-average rainfall with rising temperatures.');

  -- (Optional) update a denormalized counter, audit log, etc.
  -- UPDATE profiles SET updated_at = now() WHERE user_id = auth.uid();

COMMIT;
-- ROLLBACK; -- would undo every change above`;

/* -------------------- Concept cheat-sheet -------------------- */

export const DBMS_CONCEPTS = [
  {
    title: "DDL — Data Definition Language",
    desc: "Defines the database structure.",
    examples: ["CREATE TABLE", "ALTER TABLE", "DROP TABLE", "CREATE INDEX"],
  },
  {
    title: "DML — Data Manipulation Language",
    desc: "Reads and modifies data inside tables.",
    examples: ["SELECT", "INSERT", "UPDATE", "DELETE"],
  },
  {
    title: "DCL — Data Control Language",
    desc: "Controls access privileges.",
    examples: ["GRANT", "REVOKE", "Row-Level Security policies"],
  },
  {
    title: "TCL — Transaction Control Language",
    desc: "Manages transactions for ACID guarantees.",
    examples: ["BEGIN", "COMMIT", "ROLLBACK", "SAVEPOINT"],
  },
  {
    title: "ACID Properties",
    desc: "Atomicity, Consistency, Isolation, Durability — guaranteed by Postgres for every transaction.",
    examples: ["Atomicity: all-or-nothing", "Consistency: constraints always hold", "Isolation: concurrent txns don't interfere", "Durability: committed data survives crashes"],
  },
  {
    title: "Keys",
    desc: "Identify rows uniquely.",
    examples: ["Super Key", "Candidate Key", "Primary Key", "Foreign Key", "Composite Key", "Surrogate Key"],
  },
  {
    title: "Normalization",
    desc: "Process of organizing columns to reduce redundancy and avoid update anomalies.",
    examples: ["1NF: atomic values", "2NF: no partial dependency on PK", "3NF: no transitive dependency", "BCNF: every determinant is a candidate key"],
  },
  {
    title: "Functional Dependency (FD)",
    desc: "X → Y means: knowing X uniquely determines Y. Used to drive normalization.",
    examples: ["id → display_name", "user_id → avatar_url", "(region, avg_temp, avg_rainfall) → drought_risk"],
  },
  {
    title: "Indexing",
    desc: "Auxiliary data structure (B-Tree, Hash, GIN) that speeds up lookups at the cost of write overhead.",
    examples: ["B-Tree on PK", "Unique index on user_id", "Composite index on (user_id, created_at)"],
  },
  {
    title: "Joins",
    desc: "Combine rows from multiple tables based on related columns.",
    examples: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN", "CROSS JOIN"],
  },
  {
    title: "Aggregate Functions",
    desc: "Compute a single value from a set of rows.",
    examples: ["COUNT()", "SUM()", "AVG()", "MIN()", "MAX()", "STDDEV()"],
  },
  {
    title: "Set Operations",
    desc: "Combine results of two compatible queries.",
    examples: ["UNION", "INTERSECT", "EXCEPT"],
  },
];
