import { ParsedData } from "./parseFile";

function inferMySQLType(header: string, rows: Record<string, string | number>[]): string {
  let maxLen = 0;
  let allInt = true;
  let allNum = true;
  let hasAny = false;

  for (const row of rows.slice(0, 200)) {
    const val = row[header];
    if (val === null || val === undefined || val === "") continue;
    hasAny = true;
    const str = String(val);
    if (str.length > maxLen) maxLen = str.length;

    if (typeof val === "number") {
      if (!Number.isInteger(val)) allInt = false;
    } else {
      const num = Number(val);
      if (isNaN(num)) {
        allInt = false;
        allNum = false;
      } else if (!Number.isInteger(num)) {
        allInt = false;
      }
    }
  }

  if (!hasAny) return "VARCHAR(255)";
  if (allInt) return "INT";
  if (allNum) return "DECIMAL(15,4)";
  if (maxLen > 500) return "TEXT";
  return `VARCHAR(${Math.max(50, Math.ceil(maxLen / 50) * 50)})`;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^[0-9]/, "_$&");
}

function escapeValue(val: string | number | null | undefined): string {
  if (val === null || val === undefined || val === "") return "NULL";
  if (typeof val === "number") return String(val);
  return `'${String(val).replace(/'/g, "''")}'`;
}

export function generateTableName(fileName: string): string {
  const base = fileName.replace(/\.[^.]+$/, "");
  return sanitizeName(base).toLowerCase() || "imported_data";
}

export function generateCreateTable(data: ParsedData, tableName?: string): string {
  const name = tableName || generateTableName(data.fileName);
  const columns = data.headers.map(h => {
    const colName = sanitizeName(h);
    const colType = inferMySQLType(h, data.rows);
    return `  \`${colName}\` ${colType}`;
  });

  return [
    `CREATE TABLE IF NOT EXISTS \`${name}\` (`,
    `  \`id\` INT AUTO_INCREMENT PRIMARY KEY,`,
    columns.join(",\n"),
    `);`,
  ].join("\n");
}

export function generateInsertStatements(data: ParsedData, tableName?: string, batchSize = 50): string {
  const name = tableName || generateTableName(data.fileName);
  const colNames = data.headers.map(h => `\`${sanitizeName(h)}\``).join(", ");
  const statements: string[] = [];

  for (let i = 0; i < data.rows.length; i += batchSize) {
    const batch = data.rows.slice(i, i + batchSize);
    const values = batch.map(row => {
      const vals = data.headers.map(h => escapeValue(row[h]));
      return `  (${vals.join(", ")})`;
    });
    statements.push(`INSERT INTO \`${name}\` (${colNames})\nVALUES\n${values.join(",\n")};`);
  }

  return statements.join("\n\n");
}

export function generateFullSQL(data: ParsedData, tableName?: string): string {
  const name = tableName || generateTableName(data.fileName);
  const parts = [
    `-- ============================================`,
    `-- MySQL Script generated by DataFlow`,
    `-- Table: ${name}`,
    `-- Rows: ${data.rows.length} | Columns: ${data.headers.length}`,
    `-- ============================================\n`,
    `DROP TABLE IF EXISTS \`${name}\`;\n`,
    generateCreateTable(data, name),
    `\n-- Data\n`,
    generateInsertStatements(data, name),
  ];
  return parts.join("\n");
}

export function generateDropTable(tableName: string): string {
  return `DROP TABLE IF EXISTS \`${tableName}\`;`;
}
