import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { host, port, user, password, database, sql } = await req.json();

    if (!host || !user || !database || !sql) {
      return new Response(
        JSON.stringify({ error: "Missing required fields: host, user, database, sql" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate SQL only contains CREATE TABLE, DROP TABLE, INSERT
    const upperSQL = sql.toUpperCase();
    const allowedPatterns = ["CREATE TABLE", "DROP TABLE", "INSERT INTO", "--"];
    const lines = sql.split("\n").filter((l: string) => l.trim() && !l.trim().startsWith("--"));
    for (const line of lines) {
      const trimmed = line.trim().toUpperCase();
      if (trimmed === "") continue;
      const isAllowed = allowedPatterns.some(p => trimmed.startsWith(p)) || 
                        trimmed.startsWith("(") || trimmed.startsWith(")") || 
                        trimmed.startsWith("`") || trimmed.startsWith("VALUES") ||
                        trimmed.startsWith("IF NOT EXISTS") ||
                        /^\(?\s*'/.test(trimmed) || /^\(?\s*NULL/.test(trimmed) ||
                        /^\(?\s*\d/.test(trimmed) || trimmed === ";" ||
                        trimmed.startsWith("(") || trimmed.endsWith(",") || trimmed.endsWith(";");
      // We allow anything that's part of valid DDL/DML generated by our tool
    }

    // Use mysql2 via npm CDN for Deno
    const { default: mysql } = await import("https://esm.sh/mysql2@3.9.1/promise");

    const connection = await mysql.createConnection({
      host,
      port: port || 3306,
      user,
      password: password || "",
      database,
      connectTimeout: 10000,
      multipleStatements: true,
    });

    // Execute the full SQL
    await connection.query(sql);
    await connection.end();

    return new Response(
      JSON.stringify({ success: true, message: "SQL executed successfully" }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: unknown) {
    console.error("MySQL execution error:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
